# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "tiktok-pixel"
client_id = "c94793682c81acae38b93022f9c5369a"
application_url = "https://8e48-154-192-195-108.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://8e48-154-192-195-108.ngrok-free.app/authenticate" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "haseeb009.myshopify.com"
