import Accordion from '../../../Components/Accordion/Accordion';
import { Card, Page } from '@shopify/polaris';

function PixelFaqs() {
    const accordionItems = [
    {
      title: "How does Pixel work?",
      content: "Shortly allows you to create custom short links for your marketing campaigns, which can then be tracked for clicks and sales using Shortly's advanced analytics tools.",
    },
    {
      title: 'Can my Pixel be expired?',
      content: 'No. Links created with your own store domains will never expire and will never stop working unless you closed the store or delete your links.',
    },
    {
      title: 'Will my Pixel stop working if I uninstall the Shortly app?',
      content: 'Yes, you can use Shortly to track the clicks and sales generated by your influencer campaigns.',
    },
  ];
  return (
    <Page
    title="Faq"
  >
   <div className='marginTop20'>
    <Card>
    <Accordion items={accordionItems} />
    </Card>
   </div>
   </Page>
  );
}
export default PixelFaqs;